
#######
#
# ScryGan Parameters
#
# Recommend copying default_params.yaml to params.yaml to make changes to the parameters.
# These are the best hyperparamters so far when processing audio files from 2006 Orchive.
#
#######

# Number of training steps.
num_steps: 100000

# Number of steps between saving.
save_interval: 10

# How many audio files to process at once.
batch_size: 144

# Learning rate for training.
g_learning_rate: 0.0002
d_learning_rate: 0.0001

model:
  d_lstm_layers: 1
  d_lstm_hidden: 256
  g_lstm_layers: 1
  g_lstm_hidden: 256
  gf_dim: 128
  df_dim: 64
  z_dim: 128

# How many samples to read per timestep.
sample_size: 48000

# How much to overlap samples. Negative values to skip.
overlap_size: -48000

# Number of steps to run through the RNN.
num_t: 16

# Change z for each t
fast_z: 128

# Select the optimizer.
optimizer: adam

# Maximum amount of checkpoints that will be kept alive.
max_to_keep: 5
