
#######
#
# ScryGan Parameters
#
# Recommend copying default_params.yaml to params.yaml to make changes to the parameters.
# These are the best hyperparamters so far when processing audio files from 2006 Orchive.
#
#######

# Number of training steps.
num_steps: 10000

# How many audio files to process at once.
batch_size: 144

# Learning rate for training.
g_learning_rate: 0.0002
d_learning_rate: 0.0001

model:
  n_lstm_layers: 1
  n_lstm_hidden: 32
  gf_dim: 64
  df_dim: 64
  gfc_dim: 1024
  dfc_dim: 1024
  z_dim: 100

# How many samples to read per timestep.
sample_size: 16000

# Select the optimizer.
optimizer: adam

# Specify the momentum to be used by sgd or rmsprop optimizer. Ignored by the adam optimizer.
momentum: 0.9

# Maximum amount of checkpoints that will be kept alive.
max_to_keep: 5
